menu:
    # Home: /
    # Archive: /archives/
    # About: "http://jeremyfan.name"
    카카오톡 문의: "https://www.ttmkt.com/kakao/"

title: TrendTalk
description: TrendTalk Docs

favicon: /favicon.ico

# Copyright Infomation
# startyear: 2017
